//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintenance
    {
        public int maintenanceId { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
        public string userId { get; set; }
        public string maintencanceOrderDetails { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
